### ISSUE TITLE
issue while uninstalling

### ISSUE THREAD

**Issue by slunecniborecek** [JoshuaWise/javascript-ultimate#3] opened 2015-03-19 09:10 UTC
hi,

I removed 'javascript ultimate' plugin without closing js files and user settings update first... 

Since then every time I open ST I see the error message: "Error loading syntax file "packages/javascript ultimate/JSON.tmLanguage": Unable to open Packages\javascript ultimate\JSON.tmLanguage"

I've tried to update the user settings to un-ignore the javascript, and remove the plugin again, but error persists even after another couple of restarts.

edit: Same happens with the new install/remove with proper steps

Can you please help me with that boring issue?

**Comment by JoshuaWise** [comment] 2015-03-19 21:10
I can't reproduce this. Which version of Sublime Text are you using?

**Comment by slunecniborecek** [comment] 2015-03-20 05:02
As you asked, I realized there was an update yesterday for dev channel, build 3077 -> with this build I got these errors. But ST released a patch build 3078 later yesterday fixing somu plugin_host regression which seems to work properly now. I have no other issue for you ;) Thanks for your time

**Comment by JoshuaWise** [comment] 2015-03-20 06:48
Great! Glad to hear it's fixed now.

**Closed as completed by JoshuaWise** 2015-03-20 06:48 UTC
